"""Add missing columns to Artist table

Revision ID: 66ce65fa5e3b
Revises: d12cbb4536d4
Create Date: 2020-04-19 20:19:47.048524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66ce65fa5e3b'
down_revision = 'd12cbb4536d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('seeking_description', sa.Text(), nullable=True))
    op.add_column('Artist', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('Artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.alter_column('Artist', 'genres',
               type_=sa.ARRAY(sa.String()),
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               postgresql_using='genres::varchar[]')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'genres',
               type_=sa.VARCHAR(length=120),
               existing_type=sa.ARRAY(sa.String()),
               nullable=True,
               postgresql_using='genres::varchar[120]')
    op.drop_column('Artist', 'website')
    op.drop_column('Artist', 'seeking_venue')
    op.drop_column('Artist', 'seeking_description')
    # ### end Alembic commands ###
